QUICK_PLUS_VERSION = 0.1.0
QUICK_PLUS_MAJOR = $$section(QUICK_PLUS_VERSION, ., 0, 0)
QUICK_PLUS_MINOR = $$section(QUICK_PLUS_VERSION, ., 1, 1)
QUICK_PLUS_PATCH = $$section(QUICK_PLUS_VERSION, ., 2, 2)
DEFINES += QUICK_PLUS_VERSION=\\\"$$QUICK_PLUS_VERSION\\\"
