set(MODULES_PATH  ${CMAKE_SOURCE_DIR}/modules/Ubuntu)

list(APPEND TEST_INCLUDE_DIRS
    ${MODULES_PATH}/Layouts/plugin
)

list(APPEND TEST_COMPILE_DEFINITIONS
    QUICK_TEST_SOURCE_DIR=\"${CMAKE_CURRENT_SOURCE_DIR}\"
)

list(APPEND TEST_TARGET_LINK_LIBRARIES
    UbuntuLayouts
)
